### ISSUE TITLE
Measured temperature refresh not working

### ISSUE THREAD

**Issue by S7EN** [fbeek/pimatic-maxcul#13]
The measured temperature does not change automatically. Sometimes, after hours, when i press a comfy or off button it changes but not automatically.

**Comment by fbeek** [comment]
This is correct. The devices send their temp only if a button is pressed or settings have changed to save power. Only if they where connected to a Wallthermostat they send there Data every hour. For a continues measurement we need to implement a fake Wallthermostat and connect this to the devices.

**Comment by medolino2009** [comment]
yo can make rule that automatically changes value... something like this...

set temp of woonkamer-thermostaat to $woonkamer-thermostaat.temperatureSetpoint +1°C and after 2 minutes set temp of woonkamer-thermostaat to $woonkamer-thermostaat.temperatureSetpoint -1°C

**Comment by S7EN** [comment]
i made a rule like this, but it does not work correctly at the moment. I receive LOFV Messages after the second thermostat.

if every 1 hour

set temp of Heizung Wohnzimmer Links to $heizung-wohnzimmer-links.temperatureSetpoint +1°C and after 30 seconds set temp of Heizung Wohnzimmer Rechts to $heizung-wohnzimmer-rechts.temperatureSetpoint +1°C and after 30 seconds set temp of Heizung Bad to $heizung-bad.temperatureSetpoint +1°C and after 30 seconds set temp of Heizung Schlafzimmer to $heizung-schlafzimmer.temperatureSetpoint +1°C and after 2 minutes set temp of Heizung Wohnzimmer Links to $heizung-wohnzimmer-links.temperatureSetpoint -1°C and after 30 seconds set temp of Heizung Wohnzimmer Rechts to $heizung-wohnzimmer-rechts.temperatureSetpoint -1°C and after 30 seconds set temp of Heizung Bad to $heizung-bad.temperatureSetpoint -1°C and after 30 seconds set temp of Heizung Schlafzimmer to $heizung-schlafzimmer.temperatureSetpoint -1°C

**Comment by fbeek** [comment]
As i said in an other issue the LOFV means that you are sending to many packets. You could reach this limit very easily with only a few Devices.

Look here for a detailed definition [Link](https://wiki.fhem.de/wiki/LOVF).
This is nothing that could be fixed by the Plugin, it is a rule given by law. The only possibility would be to change the message queue so that it saves the messages and retransmits them when there where new contingents available. But this would not change anything, because it only secures that the messages would be send later when there ist a new free timeslot.

Even with the original cube and the original software it can last over 5 hours to transfer the complete weekprogramm to ONE device, because of this stupid rule.

Your only option is to reduce the amount of packets send oder patch the cul firmware and remove the limit, which is not recommended an could be illegal.

**Comment by dasmaetthes** [comment]
I have seen you implemented a fake wall thermostat. I wanted to use it to get each hour the current temperature of my device. But for the device and the fake wall thermostat device it shows me only the reference temperature I set up. Is it still not possible to get a continues measurement?
