### ISSUE TITLE
Max! Thermostat Basic auto mode

### ISSUE THREAD

**Issue by dasmaetthes** [fbeek/pimatic-maxcul#27]
Hallo,
I'm using the Max! Thermostat Basic in auto mode.
The thermostat switches from eco to comfort mode each day at 6:00 AM even I have defined no rule for that.
Can it be some default factory settings on thermostat itself? And how could I change it?

**Comment by fbeek** [comment]
Hello,
The modules have a default factory program.

Until now there is now way via maxcul to change the default programm and we do not plan to support the auto mode, because the protocol to transport the week programs is very complex an we have no user friendly option to support this in the pimatic gui.

Every known user has implemented there weekprograms via pimatic rules, this is the easiest way. 

Simply use the Manuel Mode and use pimatic to control everything

**Comment by dasmaetthes** [comment]
Thank you,

I didn't know so far that with pimatic it would work also in manuel mode. 
Then the problem is solved.
