### ISSUE TITLE
Upgrade to Serialport 6.0.x ?!

### ISSUE THREAD

**Issue by Apollon77** [fbeek/pimatic-maxcul#35]
You use a quite old version of serialport ... The most current version has much better on compile and such.

In Theory it's only that the ReadLine-parser needs to be handled differently and the options on Serialport init nees to be camel case

**Comment by fbeek** [comment]
Thank you for your message.

At the moment i do not plan to upgrade the version until pimatic is prepared for node 8.
Such an upgrade would need a lot off testing because it is a base component of the plugin and it is a  little bit sensitive.

At the moment there is no time and no need for such a big task and it is working nicely with the actual version.

As the motto says "Never touch a running system", so i will wait until it is really necessary.

But feel free to open an pull request.
