### ISSUE TITLE
Max Wall-Thermostat switch not back to temperatureSetpoint when closing the shutter contact

### ISSUE THREAD

**Issue by mabe1983** [fbeek/pimatic-maxcul#36]
I have in one room a Max wall thermostat, a thermostat and two window contacts. All devices are linked (the thermostat with wall thermostat and the window contacts, the wall thermostat with the thermostat and the window contacts, and the window contacts with the thermostat and the wall thermostat). When I open a window, the display on the wall thermostat and thermostat shows the window open symbol and the temperature of the two thermostats is lowered to 12 ° C. **But when I close the window afterwards, only the thermostat is set back to the original temperature - the wall thermostat will stay at 12 ° C and will not be set back to the original temperature**

**Comment by fbeek** [comment]
I am sorry but i cannot analyze this at the moment because i do not own or use a wall thermostat.

Eventually @treban can help here?

**Comment by treban** [comment]
I only have a wall thermostat and use fake window sensors. But i have a similar problem with 
one wall thermostat.

this thermostat has been remained switched off sometime after a window event and 
then also turned off the heating after a short time. 

I found out that it only happens when the window open temperature is not the same as the wall thermostat. so I didn't notice it at the beginning, because I didn't change the window open temperature everywhere. 
The wall thermostat must have the same WindowOpen temperature as the thermostats. 
I have added the option in my source code. 

After a factory reset, pairing all togother and set GroupID and WindowOpenTemp for all device over sendConfig, the event handling seems to be stable.

@fbeek The wallthermostat device schema needs only the "windowOpenTemperature" option. 
Then its configurable.

**Comment by mabe1983** [comment]
Thank you @treban,
that was the solution for the problem. I also adjusted the code and added the "windowOpenTemperature" in the device schema and now it works.

**Comment by treban** [comment]
You're welcome.

**Comment by fbeek** [comment]
Thanks @treban for your research and the solution.
I added the option and released v1.0.6
